In [1]:
#problem from https://milliams.com/courses/numpy_simulation/Summary.html
import numpy as np

def initialise_state(num_steps, array_size, initial_state):
    cells = np.zeros((num_steps, array_size), dtype="uint8")  # this dtype holds integers from 0-255
    cells[0] = initial_state
    return cells
    
#if the cell to the left has the same value as the cell to the right, the new value of this cell should be 0;
#if the cell to the left has a different value to the cell to the right, the new value of this cell should be 1.
def update_state(previous_array):
    new_array = np.zeros_like(previous_array)
    length = previous_array.shape[0]
    
    for i in range(length):
        index_of_cell_to_left = i - 1
        index_of_cell_to_right = i + 1
        #leftside of cell
        if index_of_cell_to_left < 0: 
            index_of_cell_to_left = 0
        #rightside of cell
        if index_of_cell_to_right >= length: 
            index_of_cell_to_right = length-1

        if previous_array[index_of_cell_to_left] == previous_array[index_of_cell_to_right]:
            new_array[i]=0
        else:
            new_array[i]=1

    return new_array

def run_simulation(num_steps, array_size, initial_state):
    state = initialise_state(num_steps, array_size, initial_state)

    for t in range(1, num_steps):
        state[t] = update_state(state[t-1])

    return state
    
#Run a simulation for an array of size 100, for 50 time steps. The initial value of the array should be all 0s, except a single 1 at index 50.
number_of_steps = 50
initial_state = [0 for i in range(50)]+[1]+[0 for i in range(50)]
array_size = len(initial_state)

cells = run_simulation(number_of_steps, len(initial_state), initial_state)

print(cells)

np.savez_compressed("infection_simulation_FinalExercise", state=cells)

[[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 1 ... 1 0 0]
 [0 1 0 ... 0 1 0]]


In [2]:
import numpy as np

with np.load("infection_simulation_FinalExercise.npz") as f:
    cells = f["state"]

In [3]:
import matplotlib.pyplot as plt
from matplotlib.colors import ListedColormap

# Set up the initial figure and axes
fig, ax = plt.subplots(constrained_layout=True)
ax.axis("off")

cmap = ListedColormap(["#029e73", "#de8f05"])

# Plot the initial grid
array_plot = ax.imshow(
    [cells[0]],  # Make our data 2-D
    vmin=cells.min(),
    vmax=cells.max(),
    animated=True,
    cmap=cmap
)

In [4]:
def animate(i):
    array_plot.set_array([cells[i]])
    return [array_plot]

In [5]:
from matplotlib.animation import FuncAnimation
from IPython.display import HTML

# Create an animation object which:
# - animate the Figure, `fig`
# - using the function `animate`
# - for len(cells) number of frames
# - where each frame lasts 100 milliseconds
anim = FuncAnimation(fig, animate, frames=len(cells), interval=100)

# Display the animation in the notebook
HTML(anim.to_jshtml())